name: GameCI Template 🎮

on: push

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  checkLicense:
    name: Check for Unity Licence
    runs-on: ubuntu-latest
    steps:
        - name: Fail - No License
          if: ${{ !startsWith(secrets.UNITY_LICENSE, '<') }}
          run: exit 1
          
  
